### ISSUE TITLE
XML support removed without proper replacement

### ISSUE THREAD

**Issue by aiphee** [nette-intellij/intellij-latte#203]
XML support was removed but only replacement seems to be manual adding of tags.

*Why it bothers us?*
Our projects contains tens of macros for rendering components etc. I cannot ask every coleague current and new to click out all the macros and filters. 
Not just it is tedious but also can lead to missclick if it is paired or unpaired macro and fixing means going to settings.

Removal of XML also closes door to autocompleting parametrs of macros which XML supported but plugin not yet implemented.

As far as i know, even the pro version doesnt offer replacement. 
Can you please explain the decission to remove XML properly? Thanks.

**Comment by mesour** [comment]
XML configuration was removed because it was bad implemented here and there were problems with it, it was main reason. And I also see it as a feature for teams and therefore one that should only be in the Pro version.

Pro version offers replacement: https://mesour-intellij-plugins.github.io/latte.html#xml-config and it has more options. And here https://mesour-intellij-plugins.github.io/latte.html#migration is also migration guide where is described what has been changed compared to the free version.
