### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by Olicek** [nette-intellij/intellij-latte#31]
Would be possible make some suggestions? I can imageine something like phpDoc notaion

```
{** @var \Entity\User $test *}
// comment above would suggest public methods and properties from \Entity\User entity
{$test->}
```

Is this possible and valid for this plugin?

**Comment by JanTvrdik** [comment]
Yes, feel free to send PR.

**Comment by dakorpar** [comment]
@JanTvrdik @matej21  I believe this feature is one of most important. If we do some campaign and find some people who are willing to put some money into it (I definitivelly am and believe many more people would also pay for this) would you implement this? Sadly my knowledge of Java and PHPStorm framework is non existant but this is something I would really like to see. It's something that's really missing!

**Comment by mesour** [comment]
It is possible from 1.0.0

**Comment by dakur** [comment]
@mesour Is there any reason for choosing macro-way (`{varType}`) over annotation (`{** @var *}`)? Could not find any mention about it. Thanks.

**Comment by mesour** [comment]
@dakur because comments in Latte starts with `{*` and ends with `*}`. It would be unnecessary to refactor comment handling in Latte and also in parser in the plugin. Therefore, a new tag `varType` has been created.

**Comment by dakorpar** [comment]
Plus I believe with latte 2.7 this will be completelly supported and probably with using strict template will also give exception, maybe there's even phpstan extension planned, so this is not just on this plugin level, but on latte level.

**Comment by dakur** [comment]
@mesour But isn't this misuse of what macros meant to be for just because "it would need more work"? Isn't it similar if someone started to use functions in PHP to type variables (`type() int $abcd`) just because `/**/` would need more work to distinguish comment from annotation? I personally understand macros as kind of functions which *do* something, whereas typing is just *describing* stuff, not doing something.

**Comment by mesour** [comment]
@dakur thanks.

I think it is not the same as in PHP. Because in Latte are used macros (now named as "tags"). And only in these tags you can use PHP. I think of a tag as a placeholder for certain code in PHP and it can also be an @var annotation. I originally wanted `{** ... *}` but then someone told me it would be better via tag. David did not object to `varType` when I asked about the implementation of Latte. It also makes sense to me with other tags for types like `templateType`.
