### ISSUE TITLE
Value variable from n:foreach is unrecognized in n:class on the same tag

### ISSUE THREAD

**Issue by dakur** [nette-intellij/intellij-latte#58]
![image](https://user-images.githubusercontent.com/9862581/76893382-8b4cd580-688c-11ea-991a-e089f4e3adf9.png)

In my case, `$section` is an object. If I write `$section->` and press `Ctrl+Space` to get suggestions, it returns tooltip with `No suggestions`.

**Comment by mabar** [comment]
It's not clear whether `$sections` type is defined in var, varType or templateType or not.

**Comment by dakur** [comment]
@mabar Oh, sorry, I forgot to list it. It's defined throug `{templateType}`.

**Comment by mesour** [comment]
@dakur it is working for me. Maybe you have properties in templateType class `private`? Plugin will use only `public` properties.

**Comment by dakur** [comment]
@mesour Aha, you're right. I have `public` property in `templateType`, but its properies are `private` with `__get()` implemented and `@property-read` annotated. So maybe that is the problem I guess it does not take annotations into account. Should I open new issue or change this one?

**Comment by mesour** [comment]
@dakur OK I will try it with annotation

**Comment by mesour** [comment]
@dakur oh, now I understand.

- :one: I tested it and variables from `@property-type` annotations are recognized. Here is no problem.
- :two: Have you variable `sections` defined like iterable type `Section[]` in template class?
  - If yes, iterable types are not implemented and will be in future: https://github.com/nette-intellij/intellij-latte/milestone/1
- :three: For future you have to use attribute `n:class` after attribute `n:foreach`
  - Because plugin check offset for variables in a file and use only definitions before variable usage.

**Comment by dakur** [comment]
ad 2) Yes, I do. So that is the problem.  
ad 3) Aha, thanks. It makes sense semantically as well.
