### ISSUE TITLE
Inspections for iterable types

### ISSUE THREAD

**Issue by mesour** [nette-intellij/intellij-latte#78]
- [x] For checking foreach value, must be array or iterable
- [x] If use array access, it must be iterable type

**Comment by lulco** [comment]
would this cover also Nette\Database\Table\Selection?

**Comment by mesour** [comment]
@lulco What do you mean? What exactly?

**Comment by lulco** [comment]
I mean for example \Nette\Database\Table\Selection or other classes implementing \Iterator:

If I use this:
```latte
{varType Nette\Database\Table\Selection $files}
```
I got error: 
```Invalid argument supplied to 'foreach'. Expected types: 'array' or 'object', '\Nette\Database\Table\Selection' provided.```

We know that all items in $files are ActiveRows from annotation of current() method. There is also "false" type but it could be ignored in foreach imho because it will never happen.

**Comment by mesour** [comment]
@lulco yes, I think you mean this issue: https://github.com/nette-intellij/intellij-latte/issues/86 :)

**Comment by lulco** [comment]
Yes, that's it :)
