### ISSUE TITLE
function this not found when generating link with (expand)

### ISSUE THREAD

**Issue by adaamz** [nette-intellij/intellij-latte#97]
![image](https://user-images.githubusercontent.com/4347332/85027756-8c86ea80-b17a-11ea-9474-d9ea37d9e5ad.png)
version 1.1.0-rc3

**Comment by mesour** [comment]
@adaamz fixed in **1.1.0-rc4** - downloadable in one-two days from https://plugins.jetbrains.com/plugin/7457-latte/versions (EAP version)

It is now recognized as a link.
![Snímek obrazovky 2020-06-27 v 12 39 43](https://user-images.githubusercontent.com/1161897/85920374-6694d080-b873-11ea-931b-af9af5093bc9.png)
